#!/bin/bash

for file in $(git diff --name-only --staged); do
    if [dirname $file == "src" && echo basename $file | sed 's/^.*\.\([^\.]*\)$/\1/' == "rs"]; then
        rustfmt $file
        git add $file
    fi
done
