#!/bin/bash

for file in $(git diff --name-only --staged); do
    dir=`dirname $file`
    if [$dir == "src" && echo basename $file | sed 's/^.*\.\([^\.]*\)$/\1/' == "rs"]; then
        rustfmt $file
        git add $file
    fi
done
