[tasks.setup]
description = "Project Setup"
script = ['''
#!/usr/bin/env bash
git config core.hooksPath .githooks
''']

[tasks.it]
description = "Run Integration Test"
script = ['''
#!/usr/bin/env bash
sh test/integration_test.sh
''']

[tasks.ut]
description = "Run Test"
script = ['''
#!/usr/bin/env bash
cargo test -- --nocapture
(cd test/server && cargo build)
''']

[tasks.pub]
description = "Publish Module"
script = ['''
#!/usr/bin/env bash
cargo publish
''']
