[tasks.setup]
description = "Project Setup"
script = ['''
#!/usr/bin/env bash
git config core.hooksPath .githooks
''']

[tasks.ut]
description = "Run Test"
script = ['''
#!/usr/bin/env bash
cargo test -- --nocapture
''']

[tasks.pub]
description = "Publish Module"
script = ['''
#!/usr/bin/env bash
cargo publish
''']

[tasks.get1]
description = "Get /path"
script = ['''
#!/usr/bin/env bash
curl localhost:3000/path
''']

[tasks.get2]
description = "Get /user/23"
script = ['''
#!/usr/bin/env bash
curl localhost:3000/user/23
''']

[tasks.get3]
description = "Get invalid path"
script = ['''
#!/usr/bin/env bash
curl localhost:3000/*0---
''']
