name: Rust Cargo Test

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sh test/integration_test.sh
